server:
  port: 9090
# https://post.naver.com/viewer/postView.nhn?volumeNo=27845264&memberNo=2490752

spring :
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
      data: classpath:schema-h2.sql # ,classpath:data-h2.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
        hibernate.default_batch_fetch_size: 1000 # https://jojoldu.tistory.com/457
    hibernate:
      ddl-auto: update #none

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  ##### Mysql 사용시
  # datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8
  #    username: htofu
  #    password: htofu
  #
  # jpa:
  #    database: mysql
  #    database-platform: org.hibernate.dialect.MySQL8Dialect # 8.0.21 version
  #    hibernate:
  #      ddl-auto: create # 옵션은 확인 필수
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true
  #        ﻿use_sql_comments: true

  h2:
    console:
      enabled: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  # https://gofnrk.tistory.com/82
  mail:
    host: smtp.gmail.com
    port: 587
    username: ksifsmtp@gmail.com
    password: sangs#1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocal: smtp

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      maxFileSize: 200MB
      maxRequestSize: 215MB

  rabbitmq:
    host: localhost # rabbitMQ host (docker로 띄웠음)
    port: 5672 # default port
    username: hee # default username
    password: hee # default password
  lisner:
    simple:
      concurrency: 4
      max-concurrency: 8
      retry:
        initial-interval: 5000
        max-attempt: 3


  kafka:
    bootstrap-servers: localhost:9092
app:
  topic: #received message
      foo: foo.t


app1:
  exchange:
    name: testmq1-exchange
  queue:
    name: testmq1-queue
  routing:
    key: testmq1-routing-key

#Message Queue specific configs for app2
app2:
  exchange:
    name: testmq2-exchange
  queue:
    name: testmq2-queue
  routing:
    key: testmq2-routing-key


file :
  uploadDir: C:\\upload

#로그파일 경로
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
            BasicBinder: TRACE
  ## log  파일 위치
  #config: classpath:logback-spring.xml # https://aljjabaegi.tistory.com/413

